# These are supported funding model platforms

# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
custom: ['https://www.buymeacoffee.com/KieranB', 'https://paypal.me/pools/c/8oNDxDSAQI']
